<?php

namespace App\Http\Controllers\frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FrontendController extends Controller
{
    public function index(){
        return view('frontend.index');
    }

    public function about_us(){
        return view('frontend.about_us');
    }

    public function condo_apartments(){
        return view('frontend.condo_apartments');
    }

    public function builders(){
        return view('frontend.builders');
    }

    public function services(){
        return view('frontend.services');
    }

    public function listing(){
        return view('frontend.listing');
    }

    public function contact_us(){
        return view('frontend.contact_us');
    }

    public function country(){
        $countries = [
            "AF" => ['name'=>"Afghanistan", 'nativetongue'=>"‫افغانستان"],
            "AX" => ['name'=>"Åland Islands", 'nativetongue'=>"Åland"],
            "AL" => ['name'=>"Albania", 'nativetongue'=>"Shqipëri"],
            "DZ" => ['name'=>"Algeria", 'nativetongue'=>"‫الجزائر"],
            "AS" => ['name'=>"American Samoa", 'nativetongue'=>""],
            "AD" => ['name'=>"Andorra", 'nativetongue'=>""],
            "AO" => ['name'=>"Angola", 'nativetongue'=>""],
            "AI" => ['name'=>"Anguilla", 'nativetongue'=>""],
            "AQ" => ['name'=>"Antarctica", 'nativetongue'=>""],
            "AG" => ['name'=>"Antigua and Barbuda", 'nativetongue'=>""],
            "AR" => ['name'=>"Argentina", 'nativetongue'=>""],
            "AM" => ['name'=>"Armenia", 'nativetongue'=>"Հայաստան"],
            "AW" => ['name'=>"Aruba", 'nativetongue'=>""],
            "AC" => ['name'=>"Ascension Island", 'nativetongue'=>""],
            "AU" => ['name'=>"Australia", 'nativetongue'=>""],
            "AT" => ['name'=>"Austria", 'nativetongue'=>"Österreich"],
            "AZ" => ['name'=>"Azerbaijan", 'nativetongue'=>"Azərbaycan"],
            "BS" => ['name'=>"Bahamas", 'nativetongue'=>""],
            "BH" => ['name'=>"Bahrain", 'nativetongue'=>"‫البحرين"],
            "BD" => ['name'=>"Bangladesh", 'nativetongue'=>"বাংলাদেশ"],
            "BB" => ['name'=>"Barbados", 'nativetongue'=>""],
            "BY" => ['name'=>"Belarus", 'nativetongue'=>"Беларусь"],
            "BE" => ['name'=>"Belgium", 'nativetongue'=>"België"],
            "BZ" => ['name'=>"Belize", 'nativetongue'=>""],
            "BJ" => ['name'=>"Benin", 'nativetongue'=>"Bénin"],
            "BM" => ['name'=>"Bermuda", 'nativetongue'=>""],
            "BT" => ['name'=>"Bhutan", 'nativetongue'=>"འབྲུག"],
            "BO" => ['name'=>"Bolivia", 'nativetongue'=>""],
            "BA" => ['name'=>"Bosnia and Herzegovina", 'nativetongue'=>"Босна и Херцеговина"],
            "BW" => ['name'=>"Botswana", 'nativetongue'=>""],
            "BV" => ['name'=>"Bouvet Island", 'nativetongue'=>""],
            "BR" => ['name'=>"Brazil", 'nativetongue'=>"Brasil"],
            "IO" => ['name'=>"British Indian Ocean Territory",'nativetongue'=>""],
            "VG" => ['name'=>"British Virgin Islands", 'nativetongue'=>""],
            "BN" => ['name'=>"Brunei", 'nativetongue'=>""],
            "BG" => ['name'=>"Bulgaria", 'nativetongue'=>"България"],
            "BF" => ['name'=>"Burkina Faso", 'nativetongue'=>""],
            "BI" => ['name'=>"Burundi", 'nativetongue'=>"Uburundi"],
            "KH" => ['name'=>"Cambodia", 'nativetongue'=>"កម្ពុជា"],
            "CM" => ['name'=>"Cameroon", 'nativetongue'=>"Cameroun"],
            "CA" => ['name'=>"Canada", 'nativetongue'=>""],
            "IC" => ['name'=>"Canary Islands", 'nativetongue'=>"islas Canarias"],
            "CV" => ['name'=>"Cape Verde", 'nativetongue'=>"Kabu Verdi"],
            "BQ" => ['name'=>"Caribbean Netherlands", 'nativetongue'=>""],
            "KY" => ['name'=>"Cayman Islands", 'nativetongue'=>""],
            "CF" => ['name'=>"Central African Republic",'nativetongue'=>"République centrafricaine"],
            "EA" => ['name'=>"Ceuta and Melilla", 'nativetongue'=>"Ceuta y Melilla"],
            "TD" => ['name'=>"Chad", 'nativetongue'=>"Tchad"],
            "CL" => ['name'=>"Chile", 'nativetongue'=>""],
            "CN" => ['name'=>"China", 'nativetongue'=>"中国"],
            "CX" => ['name'=>"Christmas Island", 'nativetongue'=>""],
            "CP" => ['name'=>"Clipperton Island", 'nativetongue'=>""],
            "CC" => ['name'=>"Cocos (Keeling] Islands", 'nativetongue'=>"Kepulauan Cocos (Keeling]"],
            "CO" => ['name'=>"Colombia", 'nativetongue'=>""],
            "KM" => ['name'=>"Comoros", 'nativetongue'=>"‫جزر القمر"],
            "CD" => ['name'=>"Congo (DRC]", 'nativetongue'=>"Jamhuri ya Kidemokrasia ya Kongo"],
            "CG" => ['name'=>"Congo (Republic]", 'nativetongue'=>"Congo-Brazzaville"],
            "CK" => ['name'=>"Cook Islands", 'nativetongue'=>""],
            "CR" => ['name'=>"Costa Rica", 'nativetongue'=>""],
            "CI" => ['name'=>"Côte d’Ivoire", 'nativetongue'=>""],
            "HR" => ['name'=>"Croatia", 'nativetongue'=>"Hrvatska"],
            "CU" => ['name'=>"Cuba", 'nativetongue'=>""],
            "CW" => ['name'=>"Curaçao", 'nativetongue'=>""],
            "CY" => ['name'=>"Cyprus", 'nativetongue'=>"Κύπρος"],
            "CZ" => ['name'=>"Czech Republic", 'nativetongue'=>"Česká republika"],
            "DK" => ['name'=>"Denmark", 'nativetongue'=>"Danmark"],
            "DG" => ['name'=>"Diego Garcia", 'nativetongue'=>""],
            "DJ" => ['name'=>"Djibouti", 'nativetongue'=>""],
            "DM" => ['name'=>"Dominica", 'nativetongue'=>""],
            "DO" => ['name'=>"Dominican Republic", 'nativetongue'=>"República Dominicana"],
            "EC" => ['name'=>"Ecuador", 'nativetongue'=>""],
            "EG" => ['name'=>"Egypt", 'nativetongue'=>"‫مصر"],
            "SV" => ['name'=>"El Salvador", 'nativetongue'=>""],
            "GQ" => ['name'=>"Equatorial Guinea",'nativetongue'=>"Guinea Ecuatorial"],
            "ER" => ['name'=>"Eritrea", 'nativetongue'=>""],
            "EE" => ['name'=>"Estonia", 'nativetongue'=>"Eesti"],
            "ET" => ['name'=>"Ethiopia", 'nativetongue'=>""],
            "FK" => ['name'=>"Falkland Islands", 'nativetongue'=>"Islas Malvinas"],
            "FO" => ['name'=>"Faroe Islands", 'nativetongue'=>"Føroyar"],
            "FJ" => ['name'=>"Fiji", 'nativetongue'=>""],
            "FI" => ['name'=>"Finland", 'nativetongue'=>"Suomi"],
            "FR" => ['name'=>"France", 'nativetongue'=>""],
            "GF" => ['name'=>"French Guiana", 'nativetongue'=>"Guyane française"],
            "PF" => ['name'=>"French Polynesia", 'nativetongue'=>"Polynésie française"],
            "TF" => ['name'=>"French Southern Territories", 'nativetongue'=>"Terres australes françaises"],
            "GA" => ['name'=>"Gabon", 'nativetongue'=>""],
            "GM" => ['name'=>"Gambia", 'nativetongue'=>""],
            "GE" => ['name'=>"Georgia", 'nativetongue'=>"საქართველო"],
            "DE" => ['name'=>"Germany", 'nativetongue'=>"Deutschland"],
            "GH" => ['name'=>"Ghana", 'nativetongue'=>"Gaana"],
            "GI" => ['name'=>"Gibraltar", 'nativetongue'=>""],
            "GR" => ['name'=>"Greece", 'nativetongue'=>"Ελλάδα"],
            "GL" => ['name'=>"Greenland", 'nativetongue'=>"Kalaallit Nunaat"],
            "GD" => ['name'=>"Grenada", 'nativetongue'=>""],
            "GP" => ['name'=>"Guadeloupe", 'nativetongue'=>""],
            "GU" => ['name'=>"Guam", 'nativetongue'=>""],
            "GT" => ['name'=>"Guatemala", 'nativetongue'=>""],
            "GG" => ['name'=>"Guernsey", 'nativetongue'=>""],
            "GN" => ['name'=>"Guinea", 'nativetongue'=>"Guinée"],
            "GW" => ['name'=>"Guinea-Bissau", 'nativetongue'=>"Guiné Bissau"],
            "GY" => ['name'=>"Guyana", 'nativetongue'=>""],
            "HT" => ['name'=>"Haiti", 'nativetongue'=>""],
            "HM" => ['name'=>"Heard & McDonald Islands", 'nativetongue'=>""],
            "HN" => ['name'=>"Honduras", 'nativetongue'=>""],
            "HK" => ['name'=>"Hong Kong", 'nativetongue'=>"香港"],
            "HU" => ['name'=>"Hungary", 'nativetongue'=>"Magyarország"],
            "IS" => ['name'=>"Iceland", 'nativetongue'=>"Ísland"],
            "IN" => ['name'=>"India", 'nativetongue'=>"भारत"],
            "ID" => ['name'=>"Indonesia", 'nativetongue'=>""],
            "IR" => ['name'=>"Iran", 'nativetongue'=>"‫ایران"],
            "IQ" => ['name'=>"Iraq", 'nativetongue'=>"‫العراق"],
            "IE" => ['name'=>"Ireland", 'nativetongue'=>""],
            "IM" => ['name'=>"Isle of Man", 'nativetongue'=>""],
            "IL" => ['name'=>"Israel", 'nativetongue'=>"‫ישראל"],
            "IT" => ['name'=>"Italy", 'nativetongue'=>"Italia"],
            "JM" => ['name'=>"Jamaica", 'nativetongue'=>""],
            "JP" => ['name'=>"Japan", 'nativetongue'=>"日本"],
            "JE" => ['name'=>"Jersey", 'nativetongue'=>""],
            "JO" => ['name'=>"Jordan", 'nativetongue'=>"‫الأردن"],
            "KZ" => ['name'=>"Kazakhstan", 'nativetongue'=>"Казахстан"],
            "KE" => ['name'=>"Kenya", 'nativetongue'=>""],
            "KI" => ['name'=>"Kiribati", 'nativetongue'=>""],
            "XK" => ['name'=>"Kosovo", 'nativetongue'=>"Kosovë"],
            "KW" => ['name'=>"Kuwait", 'nativetongue'=>"‫الكويت"],
            "KG" => ['name'=>"Kyrgyzstan", 'nativetongue'=>"Кыргызстан"],
            "LA" => ['name'=>"Laos", 'nativetongue'=>"ລາວ"],
            "LV" => ['name'=>"Latvia", 'nativetongue'=>"Latvija"],
            "LB" => ['name'=>"Lebanon", 'nativetongue'=>"‫لبنان"],
            "LS" => ['name'=>"Lesotho", 'nativetongue'=>""],
            "LR" => ['name'=>"Liberia", 'nativetongue'=>""],
            "LY" => ['name'=>"Libya", 'nativetongue'=>"‫ليبيا"],
            "LI" => ['name'=>"Liechtenstein", 'nativetongue'=>""],
            "LT" => ['name'=>"Lithuania", 'nativetongue'=>"Lietuva"],
            "LU" => ['name'=>"Luxembourg", 'nativetongue'=>""],
            "MO" => ['name'=>"Macau", 'nativetongue'=>"澳門"],
            "MK" => ['name'=>"Macedonia (FYROM]",'nativetongue'=>"Македонија"],
            "MG" => ['name'=>"Madagascar", 'nativetongue'=>"Madagasikara"],
            "MW" => ['name'=>"Malawi", 'nativetongue'=>""],
            "MY" => ['name'=>"Malaysia", 'nativetongue'=>""],
            "MV" => ['name'=>"Maldives", 'nativetongue'=>""],
            "ML" => ['name'=>"Mali", 'nativetongue'=>""],
            "MT" => ['name'=>"Malta", 'nativetongue'=>""],
            "MH" => ['name'=>"Marshall Islands", 'nativetongue'=>""],
            "MQ" => ['name'=>"Martinique", 'nativetongue'=>""],
            "MR" => ['name'=>"Mauritania", 'nativetongue'=>"‫موريتانيا"],
            "MU" => ['name'=>"Mauritius", 'nativetongue'=>"Moris"],
            "YT" => ['name'=>"Mayotte", 'nativetongue'=>""],
            "MX" => ['name'=>"Mexico", 'nativetongue'=>""],
            "FM" => ['name'=>"Micronesia", 'nativetongue'=>""],
            "MD" => ['name'=>"Moldova", 'nativetongue'=>"Republica Moldova"],
            "MC" => ['name'=>"Monaco", 'nativetongue'=>""],
            "MN" => ['name'=>"Mongolia", 'nativetongue'=>"Монгол"],
            "ME" => ['name'=>"Montenegro", 'nativetongue'=>"Crna Gora"],
            "MS" => ['name'=>"Montserrat", 'nativetongue'=>""],
            "MA" => ['name'=>"Morocco", 'nativetongue'=>"‫المغرب"],
            "MZ" => ['name'=>"Mozambique", 'nativetongue'=>"Moçambique"],
            "MM" => ['name'=>"Myanmar (Burma]", 'nativetongue'=>"မြန်မာ"],
            "NA" => ['name'=>"Namibia", 'nativetongue'=>"Namibië"],
            "NR" => ['name'=>"Nauru", 'nativetongue'=>""],
            "NP" => ['name'=>"Nepal", 'nativetongue'=>"नेपाल"],
            "NL" => ['name'=>"Netherlands", 'nativetongue'=>"Nederland"],
            "NC" => ['name'=>"New Caledonia", 'nativetongue'=>"Nouvelle-Calédonie"],
            "NZ" => ['name'=>"New Zealand", 'nativetongue'=>""],
            "NI" => ['name'=>"Nicaragua", 'nativetongue'=>""],
            "NE" => ['name'=>"Niger", 'nativetongue'=>"Nijar"],
            "NG" => ['name'=>"Nigeria", 'nativetongue'=>""],
            "NU" => ['name'=>"Niue", 'nativetongue'=>""],
            "NF" => ['name'=>"Norfolk Island", 'nativetongue'=>""],
            "MP" => ['name'=>"Northern Mariana Islands", 'nativetongue'=>""],
            "KP" => ['name'=>"North Korea", 'nativetongue'=>"조선 민주주의 인민 공화국"],
            "NO" => ['name'=>"Norway", 'nativetongue'=>"Norge"],
            "OM" => ['name'=>"Oman", 'nativetongue'=>"‫عُمان"],
            "PK" => ['name'=>"Pakistan", 'nativetongue'=>"‫پاکستان"],
            "PW" => ['name'=>"Palau", 'nativetongue'=>""],
            "PS" => ['name'=>"Palestine", 'nativetongue'=>"‫فلسطين"],
            "PA" => ['name'=>"Panama", 'nativetongue'=>""],
            "PG" => ['name'=>"Papua New Guinea", 'nativetongue'=>""],
            "PY" => ['name'=>"Paraguay", 'nativetongue'=>""],
            "PE" => ['name'=>"Peru", 'nativetongue'=>"Perú"],
            "PH" => ['name'=>"Philippines", 'nativetongue'=>""],
            "PN" => ['name'=>"Pitcairn Islands", 'nativetongue'=>""],
            "PL" => ['name'=>"Poland", 'nativetongue'=>"Polska"],
            "PT" => ['name'=>"Portugal", 'nativetongue'=>""],
            "PR" => ['name'=>"Puerto Rico", 'nativetongue'=>""],
            "QA" => ['name'=>"Qatar", 'nativetongue'=>"‫قطر"],
            "RE" => ['name'=>"Réunion", 'nativetongue'=>"La Réunion"],
            "RO" => ['name'=>"Romania", 'nativetongue'=>"România"],
            "RU" => ['name'=>"Russia", 'nativetongue'=>"Россия"],
            "RW" => ['name'=>"Rwanda", 'nativetongue'=>""],
            "BL" => ['name'=>"Saint Barthélemy", 'nativetongue'=>"Saint-Barthélemy"],
            "SH" => ['name'=>"Saint Helena", 'nativetongue'=>""],
            "KN" => ['name'=>"Saint Kitts and Nevis", 'nativetongue'=>""],
            "LC" => ['name'=>"Saint Lucia", 'nativetongue'=>""],
            "MF" => ['name'=>"Saint Martin", 'nativetongue'=>""],
            "PM" => ['name'=>"Saint Pierre and Miquelon", 'nativetongue'=>"Saint-Pierre-et-Miquelon"],
            "WS" => ['name'=>"Samoa", 'nativetongue'=>""],
            "SM" => ['name'=>"San Marino", 'nativetongue'=>""],
            "ST" => ['name'=>"São Tomé and Príncipe", 'nativetongue'=>"São Tomé e Príncipe"],
            "SA" => ['name'=>"Saudi Arabia", 'nativetongue'=>"‫المملكة العربية السعودية"],
            "SN" => ['name'=>"Senegal", 'nativetongue'=>"Sénégal"],
            "RS" => ['name'=>"Serbia", 'nativetongue'=>"Србија"],
            "SC" => ['name'=>"Seychelles", 'nativetongue'=>""],
            "SL" => ['name'=>"Sierra Leone", 'nativetongue'=>""],
            "SG" => ['name'=>"Singapore", 'nativetongue'=>""],
            "SX" => ['name'=>"Sint Maarten", 'nativetongue'=>""],
            "SK" => ['name'=>"Slovakia", 'nativetongue'=>"Slovensko"],
            "SI" => ['name'=>"Slovenia", 'nativetongue'=>"Slovenija"],
            "SB" => ['name'=>"Solomon Islands", 'nativetongue'=>""],
            "SO" => ['name'=>"Somalia", 'nativetongue'=>"Soomaaliya"],
            "ZA" => ['name'=>"South Africa", 'nativetongue'=>""],
            "GS" => ['name'=>"South Georgia & South Sandwich Islands", 'nativetongue'=>""],
            "KR" => ['name'=>"South Korea", 'nativetongue'=>"대한민국"],
            "SS" => ['name'=>"South Sudan", 'nativetongue'=>"‫جنوب السودان"],
            "ES" => ['name'=>"Spain", 'nativetongue'=>"España"],
            "LK" => ['name'=>"Sri Lanka", 'nativetongue'=>"ශ්‍රී ලංකාව"],
            "VC" => ['name'=>"St. Vincent & Grenadines", 'nativetongue'=>""],
            "SD" => ['name'=>"Sudan", 'nativetongue'=>"‫السودان"],
            "SR" => ['name'=>"Suriname", 'nativetongue'=>""],
            "SJ" => ['name'=>"Svalbard and Jan Mayen", 'nativetongue'=>"Svalbard og Jan Mayen"],
            "SZ" => ['name'=>"Swaziland", 'nativetongue'=>""],
            "SE" => ['name'=>"Sweden", 'nativetongue'=>"Sverige"],
            "CH" => ['name'=>"Switzerland", 'nativetongue'=>"Schweiz"],
            "SY" => ['name'=>"Syria", 'nativetongue'=>"‫سوريا"],
            "TW" => ['name'=>"Taiwan", 'nativetongue'=>"台灣"],
            "TJ" => ['name'=>"Tajikistan", 'nativetongue'=>""],
            "TZ" => ['name'=>"Tanzania", 'nativetongue'=>""],
            "TH" => ['name'=>"Thailand", 'nativetongue'=>"ไทย"],
            "TL" => ['name'=>"Timor-Leste", 'nativetongue'=>""],
            "TG" => ['name'=>"Togo", 'nativetongue'=>""],
            "TK" => ['name'=>"Tokelau", 'nativetongue'=>""],
            "TO" => ['name'=>"Tonga", 'nativetongue'=>""],
            "TT" => ['name'=>"Trinidad and Tobago", 'nativetongue'=>""],
            "TA" => ['name'=>"Tristan da Cunha", 'nativetongue'=>""],
            "TN" => ['name'=>"Tunisia", 'nativetongue'=>"‫تونس"],
            "TR" => ['name'=>"Turkey", 'nativetongue'=>"Türkiye"],
            "TM" => ['name'=>"Turkmenistan", 'nativetongue'=>""],
            "TC" => ['name'=>"Turks and Caicos Islands", 'nativetongue'=>""],
            "TV" => ['name'=>"Tuvalu", 'nativetongue'=>""],
            "UM" => ['name'=>"U.S. Outlying Islands", 'nativetongue'=>""],
            "VI" => ['name'=>"U.S. Virgin Islands", 'nativetongue'=>""],
            "UG" => ['name'=>"Uganda", 'nativetongue'=>""],
            "UA" => ['name'=>"Ukraine", 'nativetongue'=>"Україна"],
            "AE" => ['name'=>"United Arab Emirates", 'nativetongue'=>"‫الإمارات العربية المتحدة"],
            "GB" => ['name'=>"United Kingdom", 'nativetongue'=>""],
            "US" => ['name'=>"United States", 'nativetongue'=>""],
            "UY" => ['name'=>"Uruguay", 'nativetongue'=>""],
            "UZ" => ['name'=>"Uzbekistan", 'nativetongue'=>"Oʻzbekiston"],
            "VU" => ['name'=>"Vanuatu", 'nativetongue'=>""],
            "VA" => ['name'=>"Vatican City", 'nativetongue'=>"Città del Vaticano"],
            "VE" => ['name'=>"Venezuela", 'nativetongue'=>""],
            "VN" => ['name'=>"Vietnam", 'nativetongue'=>"Việt Nam"],
            "WF" => ['name'=>"Wallis and Futuna", 'nativetongue'=>""],
            "EH" => ['name'=>"Western Sahara", 'nativetongue'=>"‫الصحراء الغربية"],
            "YE" => ['name'=>"Yemen", 'nativetongue'=>"‫اليمن"],
            "ZM" => ['name'=>"Zambia", 'nativetongue'=>""],
            "ZW" => ['name'=>"Zimbabwe", 'nativetongue'=>""]
        ];

        return $countries;
    }
}
